export const AUTH_REQ_IN_PROGRESS = "AUTH_REQ_IN_PROGRESS";
export const AUTH_REQ_SUCCESS = "AUTH_REQ_SUCCESS";
export const AUTH_REQ_FAILURE = "AUTH_REQ_FAILURE";
export const AUTH_CLEAR = "AUTH_CLEAR";

export const USER_REQ_IN_PROGRESS = "USER_REQ_IN_PROGRESS";
export const USER_REQ_SUCCESS = "USER_REQ_SUCCESS";
export const USER_REQ_FAILURE = "USER_REQ_FAILURE";
export const USER_CLEAR = "USER_CLEAR";

export const CONTACT_REQ_IN_PROGRESS = "CONTACT_REQ_IN_PROGRESS";
export const CONTACT_REQ_SUCCESS = "CONTACT_REQ_SUCCESS";
export const CONTACT_REQ_FAILURE = "CONTACT_REQ_FAILURE";
export const CONTACT_SELECT = "CONTACT_SELECT";
export const CONTACT_DESELECT = "CONTACT_DESELECT";
