export const AUTH_REQ_IN_PROGRESS = "AUTH_REQ_IN_PROGRESS";
export const AUTH_REQ_SUCCESS = "AUTH_REQ_SUCCESS";
export const AUTH_REQ_FAILURE = "AUTH_REQ_FAILURE";
export const AUTH_CLEAR = "AUTH_CLEAR";

export const CONTACT_REQ_IN_PROGRESS = "CONTACT_REQ_IN_PROGRESS";
export const CONTACT_REQ_SUCCESS = "CONTACT_REQ_SUCCESS";
export const CONTACT_REQ_FAILURE = "CONTACT_REQ_FAILURE";
