version: "3.8"

services:
  frontend:
    container_name: contact-app-frontend
    image: contact-app-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args: 
        REACT_APP_API_URL: http://localhost:8081
    # volumes:
      # - "./frontend:/app"               # Uncomment for Dev - Mounts Frontend Codes/Files into Container
      # - "/app/node_modules"               # Uncomment for Dev - Use node_modules from Container
    ports:
      - 3001:3000
    # environment:
      # - CHOKIDAR_USEPOLLING=true        # Uncomment for Dev - enables polling mechanism via chokidar, for Hot Reload
  backend:
    container_name: contact-app-backend
    image: contact-app-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8081:8080