version: "3.8"

services:
  frontend:
    container_name: contact-app-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true